### ISSUE TITLE
Add filtering bar

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#101]
<img width="830" alt="image 2016-06-27 at 9 44 43 am" src="https://cloud.githubusercontent.com/assets/105464/16530786/b1a8f294-3f97-11e6-855f-442c0cd280db.png">

**Comment by nchevobbe** [comment]
if possible, I'd like to work on this one

**Comment by linclark** [comment]
Rad! It's in the deployment-phase-1 milestone, so we're hoping to get it done by next Wednesday. But really, the only essential part for that is the hide network messages checkbox and the buttons for filtering by log level. If that works with your schedule, I'd love it if you could tackle it.

**Comment by nchevobbe** [comment]
> Rad! It's in the deployment-phase-1 milestone, so we're hoping to get it done by next Wednesday. But really, the only essential part for that is the hide network messages checkbox and the buttons for filtering by log level. If that works with your schedule, I'd love it if you could tackle it.

Yes, I can focus on it now. I'll try to have something to review by Friday or next Monday so we have time to iterate on it if I did it wrong the first time.

**Comment by bgrins** [comment]
We landed some similar changes on the old repo - I'm not sure how directly useful all of this will be but maybe some of it can be reused:

https://github.com/bgrins/console-output-experiment/commit/372164559168b8341a19708038a6f276062cd21d
https://github.com/bgrins/console-output-experiment/commit/da0505b7cefa9ad74df2064ddeebef20f49adbcf
https://github.com/bgrins/console-output-experiment/commit/f223ad2467497ab9f2da358af9fd4bdbd419caad
https://github.com/bgrins/console-output-experiment/commit/ef444846f198bca322e53348c052ff95c4d2a1a5

**Comment by bgrins** [comment]
We should also be able to pull out some of the .requests-menu-filter-button styles from the net monitor and move it into the shared toolbars.css file

**Comment by nchevobbe** [comment]
Here's the list of preference we have for the current filtering : 
- "devtools.webconsole.filter.network"
- "devtools.webconsole.filter.networkinfo"
- "devtools.webconsole.filter.netwarn"
- "devtools.webconsole.filter.netxhr"
- "devtools.webconsole.filter.csserror"
- "devtools.webconsole.filter.cssparser"
- "devtools.webconsole.filter.csslog"
- "devtools.webconsole.filter.exception"
- "devtools.webconsole.filter.jswarn"
- "devtools.webconsole.filter.jslog"
- "devtools.webconsole.filter.error"
- "devtools.webconsole.filter.warn"
- "devtools.webconsole.filter.info"
- "devtools.webconsole.filter.log"
- "devtools.webconsole.filter.secerror"
- "devtools.webconsole.filter.secwarn"
- "devtools.webconsole.filter.serviceworkers"
- "devtools.webconsole.filter.sharedworkers"
- "devtools.webconsole.filter.windowlessworkers"
- "devtools.webconsole.filter.servererror"
- "devtools.webconsole.filter.serverwarn"
- "devtools.webconsole.filter.serverinfo"
- "devtools.webconsole.filter.serverlog"

With the new design, we want to filter the severity : 
- info
- log
- warn
- error

And the category : 
- network
- cssparser

There's some type of messages that we won't cover with the new design (netxhr, sec_, serviceworkers, sharedworkers, windowlessworkers, server_), is it wanted ?

**Comment by linclark** [comment]
I'd say yes, that is correct. We no longer want those extra classifications of messages. @bgrins, do you agree?

**Comment by bgrins** [comment]
Chatted with Lin, here's what I'd say:

netxhr: let's apply the 'network' filter to these messages as well
sec: show based on the severity (error, warn)
serviceworkers: show based on severity
sharedworkers / windowlessworkers: I don't really know off hand how common these logs are - I'd say show based on severity and we can revisit if they are too frequent or unexpected
server: show based on severity

**Comment by bgrins** [comment]
@helenvholmes I'd like to clarify a couple of things about network filtering:

We have a different behavior from chrome with Net right now.  By default they appear to only show net errors when the option is enabled (no XHR or normal request logging).  There's a context menu item to toggle XHR logging - which is disconnected from the rest of the 'filtering' UI.  If I were to assign meaning to the difference it'd be that when XHR filtering is off you don't necessarily want to show the 'N messages hidden' UI, but it could well just be that the toggle is in a weird place.

On top of all of that, we have an option to show _all_ requests in the console, while they don't.  This would mean that turning on 'net' logging is quite noisy. I'm not sure what the desired behavior is here - I've seen people use the all requests feature, especially in the Browser Console but even in the web console.

My thinking right now is: we show all net errors just as errors in the console, no filtering except based on severity.  We have a "XHR" filter button next to the "CSS" one that shows / hides XHR requests.  In the browser console (maybe also web console) there's yet another button next to them called "All Net" or something that just shows all network traffic.  Any thoughts?

**Comment by bgrins** [comment]
To complete the thought in the previous comment and what it would mean for the designs - this would mean that the 'hide network messages' checkbox would go away in the filtering UI, and be replaced with a new "XHR" filter button (along with in some cases a more verbose "All Net" button).  There'd be no context menu item for toggling XHR as in chrome.

**Comment by helenvholmes** [comment]
Going to do my best to pull this apart. Bear with me:

> We have a different behavior from chrome with Net right now. By default they appear to only show net errors when the option is enabled (no XHR or normal request logging). There's a context menu item to toggle XHR logging - which is disconnected from the rest of the 'filtering' UI. If I were to assign meaning to the difference it'd be that when XHR filtering is off you don't necessarily want to show the 'N messages hidden' UI, but it could well just be that the toggle is in a weird place.
> I think that if you have XHR logging turned _off_, you wouldn't want to see the filter message. I think we want the filtering message to only apply to the severities or it becomes noisy.
> 
> On top of all of that, we have an option to show all requests in the console, while they don't. This would mean that turning on 'net' logging is quite noisy. I'm not sure what the desired behavior is here - I've seen people use the all requests feature, especially in the Browser Console but even in the web console.
> I think we want to keep this as our users are used to it. I imagined in the designs Lin posted that checking "Hide Network Messages" would toggle this all/nothing messages _with the exception_ of errors and warnings. (I can imagine there might be a scenario where users want to turn off network errors and only see javascript errors; is this scenario common enough that we want to design around it?)
> 
> My thinking right now is: we show all net errors just as errors in the console, no filtering except based on severity. We have a "XHR" filter button next to the "CSS" one that shows / hides XHR requests. In the browser console (maybe also web console) there's yet another button next to them called "All Net" or something that just shows all network traffic. Any thoughts?
> I think this makes sense. My only thought is that perhaps instead of an "All Net" button we leave it as a toggle button.

@nt1m's asked a few times why we have some filters as pills and others as checkboxes, and my thinking around it is this: 

**Pills:** These are really concise on/off switches that can express themselves in one word.
**Checkboxes:** These need additional wording to explain themselves and don't fit as well as pills. 

As an aside, I like changing the wording around to be positive—this way, toggling anything "on" is a positive action (showing the thing), toggling them "off" is a negative option (hiding the thing).

![screen shot 2016-07-12 at 10 16 35 pm](https://cloud.githubusercontent.com/assets/1720093/16789785/5e31de92-487e-11e6-8c16-caacb8065189.png)
Does this all make sense? Let me know if any of you see fault in the logic.

**Comment by nchevobbe** [comment]
we could maybe group the XHR pill and the Show All Network Message, because they are related ? 
Also, I think the Persist logs input should be the last element (maybe even sticked to the right), because it does not really alter the current messages.
So we would have something like

`Errors Warnings Logs Info | CSS | XHR  ❑ Show all Network Messages | ❑ Persist logs`

**Comment by nt1m** [comment]
@helenvholmes Your argument makes sense, but I think for consistency, it would be nicer to have a pill button. If your concern is that the wording is too long, how about shortening to [Other network messages] for the pill button?

I also agree with @nchevobbe. In addition to what he said, maybe we should put the CSS/XHR/Net stuff before the Errors/Warnings/Logs/Info buttons. It makes it more clear that those filters have the priority over the Severity (errors/warnings/...) filter.
Like this:
CSS XHR Other network messages | Errors Warnings Logs Info | ❑ Persist logs

@bgrins Now that I think of it, with the colour code going away, how are we going to distinguish server/worker logs from the normal ones ? Are we going to display a "tag" like for XHR requests ?

**Comment by helenvholmes** [comment]
Definitely think the reordering makes sense, @nchevobbe, let's definitely reorder them to make sense

![screen shot 2016-07-13 at 9 35 23 am](https://cloud.githubusercontent.com/assets/1720093/16805251/3f9f6bfc-48dd-11e6-9bef-951b0ebc7a94.png)

I still prefer the "Show All Network Messages" over the pill because I think it has clearer language, but perhaps it's more obvious than I think it is, @nt1m? (Do we have any idea what this will look like after it's localized?)

@linclark, have you decided on defaults for when people first open the console, or thought about migration paths for people currently using the FF console? I definitely want us to have sensible defaults for people on clean or not-oft-used profiles.

@nt1m, re: service workers: Chrome currently has you switch contexts between "top" and workers that I guess are registered for the current page. We might do something similar, but it might also be worth asking some people currently doing a lot of SW work what they find lacking with the current loggers.

**Comment by linclark** [comment]
I agree with @helenvholmes on "Show All Network Messages". I think we could consider getting rid of CSS messages... none of the other browsers display them in the same way we do AFAIK, and I'm not sure how much they are used. But we don't have to decide on that now.

> @linclark, have you decided on defaults for when people first open the console, or thought about migration paths for people currently using the FF console? I definitely want us to have sensible defaults for people on clean or not-oft-used profiles.

I think the default would be to have all severities/levels on and to show network messages, including XHR. I think CSS should be off (or gone) and persisting logs should be off. @bgrins, lmk if you disagree.

**Comment by bgrins** [comment]
> I think the default would be to have all severities/levels on and to show network messages, including XHR. I think CSS should be off (or gone) and persisting logs should be off. @bgrins, lmk if you disagree.

That sounds good - the only part I'm not sure about there is 'show all network messages' being o by default if the behavior of the checkbox is changed in the way I outlined in https://github.com/devtools-html/gecko-dev/issues/101#issuecomment-232220113.  The behavior of this checkbox would differ from Chrome's in that in Chrome checking that box hides network error messages: https://developers.google.com/web/tools/chrome-devtools/debug/console/console-ui#additional-settings.  But I'm thinking we should always show network error messages if the 'error' severity is included and instead change the meaning of that to be 'show all requests' (a feature that is currently off by default and should probably remain so).

**Comment by bgrins** [comment]
> But I'm thinking we should always show network error messages if the 'error' severity is included and instead change the meaning of that to be 'show all requests' (a feature that is currently off by default and should probably remain so).

If we change the behavior in this way (and feel free to argue against it), then its behavior is very much like the XHR pill.  Naming it simply is tricky, as it's basically 'show all non-xhr net requests' but if we could come up with something I think it could be a pill - maybe just 'Requests'.  I don't feel super strongly about it, I just think that it's not actually that important of a feature and we'd be giving it a lot of space as a checkbox / label (and it would look more symmetrical as a pill).

One more note: an important difference I'm envisioning that the "CSS", "XHR", and this UI element (checkbox/pill) share compared to the rest of the filtering controls is that when they are off, we wouldn't show the 'N messages hidden' filter control

**Comment by helenvholmes** [comment]
I'm fine with naming it to "Requests" if people here feel that's descriptive enough, and making it a pill. Let's do that.

I'm also fine with the filtering message—if I'm understanding correctly, you _only_ see the filtered message if you have chosen to hide a severity.

**Comment by helenvholmes** [comment]
![screen shot 2016-07-13 at 1 31 50 pm](https://cloud.githubusercontent.com/assets/1720093/16813114/2f2771f4-48fe-11e6-8ae1-8c53b1c248df.png)

**Comment by nt1m** [comment]
+1 for "Requests". If we want to be more precise, "Other Requests" could work as well.
I also think the separator between the XHR pill and the CSS pill isn't necessary, as those pills work the same way.
About localisation, "Other requests" translates to "Autres requêtes" in French, so it's not much longer, I don't know for other languages though.

@helenvholmes How do you feel about moving the CSS/XHR/Requests pills before the Severity pills (Errors/Warnings/...) ? I think it's better because it emphasizes the fact that the CSS/XHR/... pills have higher priority than the severity pills.

**Comment by nchevobbe** [comment]
Is there any special searching/filtering syntax on the search input ? Looking at the current console, it seems that all we do is lowercasing both the search term and the log messages to see if the search string is included in the log message. 

But, I see in the design "!ping spotify", which looks like a special syntax (and there's the link about that syntax).
@helenvholmes do you have something specific in mind for that ? What's the page the link leads to ?

**Comment by helenvholmes** [comment]
@nt1m If I remember everything from a conversation with Brian and Lin, I think we wanted to go with severities first because users find them more useful. Also cuts down on the number of papercuts between Chrome and Firefox.

**Comment by nt1m** [comment]
@helenvholmes Yeah, but the categories have the priority over the severities if I understand correctly. If you toggle off the CSS category, you won't see any CSS logs no matter what severity you checked.

**Comment by bgrins** [comment]
> But, I see in the design "!ping spotify", which looks like a special syntax (and there's the link about that syntax).

IIRC we were discussing eventually having an advanced search syntax (i.e. regexps and other special syntax we define).  But in v1 we should only need to target parity with the current UI.

**Comment by helenvholmes** [comment]
@nt1m true, but I'd still rather see the severities first, mostly because of the papercuts issue.

@nchevobbe, Brian's right above—I think eventually we want a special syntax to work in the filtering area but that should probably be tackled later.

**Comment by nchevobbe** [comment]
Something I thought about, does XHR is the best term we can have ? I'm saying this because of `fetch` , and I think that from a user point of view, the XHR (or whatever we call it) filtering button will act both on XmlHttpRequest and fetch request.

**Comment by bgrins** [comment]
I'm a fan of 'XHR' for now because it's consistent with our current frontend.  But mostly because I can't think of a good 1 word replacement for it.

**Comment by linclark** [comment]
Once #157, #126 and #129 are done, I think we can merge this into m-c. @nchevobbe @bgrins, any concerns? I know that @bgrins wanted to get QA on this if possible.

**Comment by bgrins** [comment]
@linclark I'd like to have a try push with Talos results including the changes in #123 to make sure the CSS changes haven't regressed.  I haven't figured out how to push to try yet from this repo - would you be able to do that (maybe make a bug to merge this filter bar work so we can trigger from mozreview)?

**Comment by linclark** [comment]
Good idea, I can get that up tonight.

EDIT: Will have to land https://bugzilla.mozilla.org/show_bug.cgi?id=1286676 before I push up to mozreview

**Comment by linclark** [comment]
I'm going to close this one out since we landed the main PR. The remaining issues that we need to complete before landing this in m-c are already marked with the sprint 2 milestone.
