### ISSUE TITLE
Mimimum viable performance

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#104]
Before we turn on in Nightly, we should make sure that performance is at least comparable to the existing console.

**Comment by bgrins** [comment]
We should support DAMP using the 'new-messages' event (similar to what we need for #99), and confirm that the console measurements don't regress with the new frontend.

This could be done with a try push where the frontend pref is flipped by default in devtools.js.

**Comment by linclark** [comment]
@bgrins does anything else need to happen for this?

**Comment by bgrins** [comment]
We need to do a try push now with talos results and compare.  Once we land everything pending in fx-team I can do that

**Comment by bgrins** [comment]
Try push: 
https://treeherder.mozilla.org/#/jobs?repo=try&revision=3f4e7790d525

Perfherder:
https://treeherder.mozilla.org/perf.html#/comparechooser?newProject=try&newRevision=3f4e7790d525

**Comment by bgrins** [comment]
Ah, getting some damp errors on the try push due to different callback args in new-messages.  Here's a new one that makes it always call with a Set:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=c74d60cc9f0a

**Comment by bgrins** [comment]
Here's the updated perfherder link (ongoing): https://treeherder.mozilla.org/perf.html#/compare?originalProject=fx-team&originalRevision=95e17b89b519&newProject=try&newRevision=c74d60cc9f0a&framework=1&filter=damp&showOnlyImportant=0
