### ISSUE TITLE
Incorporate markup changes from network request stack trace changes (Bug 1281732)

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#107]
Some changes are landing in m-c to make the structure of all message types more consistent.  See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1281732#c57:

```
message-body-wrapper
- message-flex-body
  - message-body
  - message-repeats
  - message-location
- attachment (stacktrace or consoletable)
```

I believe it also gets rid of some extra elements in the hierarchy.  We should confirm once that bug lands that our makup matches the normal frontend.

This should wait until #105 lands

**Comment by linclark** [comment]
Yes, this should definitely wait for #105 and also for us to do an update from mozilla-central. We generally would do that weekly/bi-weekly, but haven't been because of the work weeks.

**Comment by bgrins** [comment]
Maybe we can rebase once bug 1283870 lands

**Comment by linclark** [comment]
👍

**Comment by linclark** [comment]
This is ready to be worked on now.

For the person who takes this on, you should start with the commit from #109. It cleans up the component code and brings the PageError markup in line with what it was yesterday. Then it can be modified to match the current markup.

**Comment by linclark** [comment]
@jsnajdr this one should be pretty straightforward now. Do you mind giving it a look? We should be landing all of the commits from here to m-c today, so you could work on it as a patch in an hg checkout if you prefer.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1296389](https://bugzilla.mozilla.org/show_bug.cgi?id=1296389)

**Comment by jsnajdr** [comment]
@linclark Yes, you can assign this to me. Do you prefer a PR here or a standard Mozilla patch? I'm using `git-cinnabar`, so using this repo is just a matter of setting up a new remote and a branch.

**Comment by linclark** [comment]
If you don't have a preference, GitHub PR would be easier for me. Thanks!
