### ISSUE TITLE
Change [category] and [severity] to classes

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#121]
This will let us get rid of any `is=""` hacks to be able to use non-standard attributes.  We'll need to update both the new markup, old markup, and CSS all in the same patch.

**Comment by linclark** [comment]
I think we might want to remove category and severity all together. I believe the only reason we have those is for tests and for the filtering, which will be handled via Redux in the new system.

**Comment by bgrins** [comment]
I believe we also use it for controlling styling aspects of the message i.e. https://dxr.mozilla.org/mozilla-central/source/devtools/client/themes/webconsole.css#322

**Comment by linclark** [comment]
I think for that case it probably makes sense to switch to classes. What do you think?

**Comment by bgrins** [comment]
Yeah classes make more sense than data attributes.  Will rename the bug to match that

**Comment by linclark** [comment]
This will land in m-c in [Bug 1289798](https://bugzilla.mozilla.org/show_bug.cgi?id=1289798)
