### ISSUE TITLE
Improve performance by using shouldComponentUpdate

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#122]
Currently, we are calling render on each message instance with each state change. This is a pretty big performance hit as the array of messages gets larger. If we used keys and shouldComponentUpdate, then only the messages that had changed would go through render.

For the key, we may want to add an autoincremeting ID in utils/messages.js

**Comment by bgrins** [comment]
So what is the component(s) that should have the shouldComponentUpdate implementation?  And should it be comparing keys on the old and new messages?

**Comment by linclark** [comment]
We should be able to do the `shouldComponentUpdate` on the MessageContainer and it should just be able to check the `repeat` prop.

The key would be added [where we create the array of messages](https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/new-console-output/components/console-output.js#L45).

**Comment by bgrins** [comment]
@pelmers is working on this one

**Comment by pelmers** [comment]
Some test-writing progress in https://github.com/devtools-html/gecko-dev/pull/128

**Comment by linclark** [comment]
@pelmers thanks for posting the WIP, and I'm so excited to see the test in there! it will be great if we can get numbers on the kind of improvement this provides.

**Comment by bgrins** [comment]
Closed by #128
