### ISSUE TITLE
Sync changed filter prefs back to system

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#127]
Depends on #101 

In the current console, we persist the filter prefs across opening/closing of the toolbox. We need a way to write the pref back to the system.

Tests:
- Filter buttons are persisted. see browser_webconsole_bug_622303_persistent_filters.js

**Comment by bgrins** [comment]
And I don't think we need to worry about 'migrating' a users prefs for filtering into the current frontend

**Comment by linclark** [comment]
This will land in m-c in [Bug 1305788](https://bugzilla.mozilla.org/show_bug.cgi?id=1305788)
