### ISSUE TITLE
Use a button instead of a link for the VariableViewLink

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#134]
There's a similar issue described in https://bugzilla.mozilla.org/show_bug.cgi?id=1287389 : hovering the title in the devtools shows the location preview of the link, which isn't helpful since `href` is `#` ( see  https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/new-console-output/components/variables-view-link.js) . We should use a proper `button` element.
@janodvarko is going to add a CSS rule to have a button that looks like a link. We should use it when it land.

**Comment by bgrins** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=987373#c33.  We need to make sure the button is focusable from the keyboard

**Comment by nchevobbe** [comment]
I made a quick test on the VariableView and the button is indeed focusable
I was able to navigate through "button links" with the keyboard, and open the variable view pressing enter on a focused button (on OSX).

**Comment by linclark** [comment]
This will land in m-c in [Bug 1296729](https://bugzilla.mozilla.org/show_bug.cgi?id=1296729)
