### ISSUE TITLE
Follow-up: address filterbar CSS feedback

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#137]
We want to land #123, but there was some CSS feedback that still needs to be addressed. This issue is to track that.

/cc @nchevobbe

**Comment by linclark** [comment]
As part of this, we should change the word `filtering` to `filter` in class names.

**Comment by nchevobbe** [comment]
I'm working on this

**Comment by nchevobbe** [comment]
We can close this since https://github.com/devtools-html/gecko-dev/pull/157 landed

**Comment by linclark** [comment]
👍

There's some GitHub magic that can help with this. If you add the words "Fix #<issue_num>" in the PR description, then it should close this automatically when the issue is merged.
