### ISSUE TITLE
Improve performance of filtering/searching with keys

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#139]
If array indexes change in an array of children in React, it can confuse React into thinking that all of the things have changed value. See an explanation [here](https://www.youtube.com/watch?v=-t8eOoRsJ7M&feature=youtu.be&t=998);

To help with this, we should give React a key for each message.

**Comment by bgrins** [comment]
@pelmers is working on this

**Comment by linclark** [comment]
@pelmers I just realized that without this, the `shouldComponentUpdate` makes the filtering buggy. Do you think you'll be able to get to this today? If not, I can work on it.
