### ISSUE TITLE
Add new console output support for all messages

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#140]
Currently there are places where messages come in from the backend and we aren't intercepting them. For example, [network messages](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#3313). We should integrate the new console in all of these places.

**Comment by nchevobbe** [comment]
I'd like to work on this one. I think it makes sense to have this done before adding the filter for those messages (xhr and other requests).

**Comment by linclark** [comment]
Excellent! We can prioritize this for next sprint.

There's one in this sprint which is kind of related, #66. I know that you had put up a PR for that before but I wanted to hold based on Jarda's work adding the Stacktrace component and the Reps work. Would you be interested in working on that one again?

**Comment by nchevobbe** [comment]
> There's one in this sprint which is kind of related, #66. I know that you had put up a PR for that before but I wanted to hold based on Jarda's work adding the Stacktrace component and the Reps work. Would you be interested in working on that one again?

Sure, I'm gonna look right now

**Comment by linclark** [comment]
I still need to go through and create a checklist for this one, so let's hold on that. I should be able to do that tomorrow.

**Comment by linclark** [comment]
Ok, I created an issue for each of these. 

In this issue, I think we can just add the `if NEW_CONSOLE_OUTPUT_ENABLED` handling to each of the handlers in `client/webconsole.js`. 

After this, we'll need to change the handling in `utils/messages.js`. Currently, if it doesn't understand the type it defaults to handling it as an evaluation result. Instead, we should have the default case just be a blank ConsoleMessage. That should make the system route it to the `DefaultRenderer`.

**Comment by linclark** [comment]
@nchevobbe Are you working on this one? If not, I can go ahead and take it.

**Comment by nchevobbe** [comment]
I haven't done anything for now. I was planning to work on this after the #90 & #207 . But if you want to take it, go ahead

**Comment by linclark** [comment]
As I look at this closer, I think it might make sense to take care of each in their own issue. I'm going to close this one out in favor of the child issues.
