### ISSUE TITLE
Fix test/store/test_messages.js

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#141]
I think that https://github.com/devtools-html/gecko-dev/commit/36998a3b72fc99ecb99ebff37135296a584584a5 broke devtools/client/webconsole/new-console-output/test/store/test_messages.js , ( see https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/new-console-output/test/store/test_messages.js#L65 , I got message2.data is undefined )

**Comment by linclark** [comment]
Sorry about that! Moral of the story is I should double check that I've run the tests before I commit any PRs. Will have a fix up shortly

**Comment by linclark** [comment]
Fix in #143
