### ISSUE TITLE
Add title on repeat element

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#145]
See http://searchfox.org/mozilla-central/source/devtools/client/locales/en-US/webconsole.properties#213

**Comment by nchevobbe** [comment]
console uses PluralForm for the title (http://searchfox.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1137), which is currently a jsm script. I guess we should migrate this into a proper js file in light of devtools.html

**Comment by nchevobbe** [comment]
Julian is working on the PluralForm.jsm migration ( https://bugzilla.mozilla.org/show_bug.cgi?id=1265887 ). We will be able to use the new one when his patch lands.

**Comment by bgrins** [comment]
Semi-related: more webconsole localization work that will require a rebase from m-c due to a path change to the properties file https://bugzilla.mozilla.org/show_bug.cgi?id=1295609

**Comment by nchevobbe** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1265887 landed, we should be able to work on this once we merge the changes from M-C

**Comment by linclark** [comment]
Just merged in changes from m-c.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1306781](https://bugzilla.mozilla.org/show_bug.cgi?id=1306781)
