### ISSUE TITLE
Make action/function/variable names more concise/consistent

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#146]
| current | suggested | notes |
| --- | --- | --- |
| SEVERITY_FILTER | FILTER_SET | requires adding a `type` or something to the action payload |
| FILTERBAR_TOGGLE | FILTER_BAR_TOGGLE | to match the function name, filterBarToggle |
| FilterToggleButton | FilterToggle |  |
| onClearOutputButtonClick | onClickMessagesClear |  |
| onToggleFilterConfigBarButtonClick | onClickFilterBarToggle |  |
| onClearFiltersButtonClick | onClickFiltersClear |  |
| configFilterBarVisible | filterBarVisible |  |

Other notes:
- the `show` parameter can be removed from `filterBarToggle`
- I think the state that's currently on UI makes sense to be combined with the filters, but open to discussion

**Comment by linclark** [comment]
@nchevobbe what do you think of these changes? If you're ok with them, I can go ahead and make them, or lmk if they will collide with any of your current work.

**Comment by nchevobbe** [comment]
I'm fine with the name changes and getting rid of the `show` parameter for `filterBarToggle` 
For the ui state, I don't really know, I was thinking that maybe we'll have more ui action when we introduce a React version of jsterm, but I could be wrong. 
I don't have experiences using React/Redux so if you think a change is needed I trust you

**Comment by linclark** [comment]
This will be fixed with #177-#179
