### ISSUE TITLE
Add a perf subtest for tracking message filtering speed

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#155]
Depends on #154

We should extend the perf test with a subtest that tracks the time it takes to filter out half or so of the messages, then clear the filter and see how long it takes.  The `key` changes should really help with perf here.

**Comment by bgrins** [comment]
@pelmers is working on this

**Comment by pelmers** [comment]
Does this issue include the formatting of the info message to use PERFHERDER_DATA?

**Comment by bgrins** [comment]
> Does this issue include the formatting of the info message to use PERFHERDER_DATA?

Let's break that into another commit / PR and then we can get separate review from the a-team to make sure we are formatting data correctly.
