### ISSUE TITLE
Convert existing tests to mocha

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#162]
- [x] actions
- [x] components
- [x] store
- [x] utils

As part of this, perf should move to its own test directory.

**Comment by linclark** [comment]
<del>Converting the components tests is going to be a little more complicated because Reps use AMD. Our browser loader has [code](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/browser-loader.js#137) that makes this work, but when running Mocha tests the browser loader isn't involved. </del>

Turns out this isn't so hard afterall.

**Comment by linclark** [comment]
Added to sprint 2 because this will really speed up development of other tasks. I think I can get this done today.

**Comment by linclark** [comment]
This is all in review now.

**Comment by linclark** [comment]
done 🎉🎉🎉🎉🎉🎉🎉

**Comment by bgrins** [comment]
:thumbsup: nice work!
