### ISSUE TITLE
Fix filter input style for devtools' dark theme

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#167]
Currently, we keep the white background-color, which doesn't look great.

![filter_dark](https://cloud.githubusercontent.com/assets/578107/17136183/3d3f01e0-5334-11e6-8655-c4a728e12a03.png)

@helenvholmes , should I just made the background transparent, or darker, like the `filter properties` input of the variable view ?
![search_input_dark](https://cloud.githubusercontent.com/assets/578107/17136342/feb94024-5334-11e6-81f1-ceb5627e8035.png)

**Comment by helenvholmes** [comment]
@nchevobbe: my preference would be to make it transparent. I'd like to see those inputs change over to transparency in the future as we swap over to these designs that are width/height 100%.
