### ISSUE TITLE
Clear messages when navigation packet is received

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#176]
When someone navigates to a new page, we should clear the messages from the store.

**Comment by pelmers** [comment]
Is this issue a subset of #131?

**Comment by linclark** [comment]
Yes, it is. We need this part sooner than the rest, so this will stay focused on just clearing the messages in response to the navigation event.

**Comment by pelmers** [comment]
I can take this bug.

**Comment by bgrins** [comment]
I think this is already working via https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/jsterm.js#L964-L966

**Comment by bgrins** [comment]
Is there a case where messages are _not_ being cleared while navigating?  I think this is a worksforme

**Comment by linclark** [comment]
I think you are correct.
