### ISSUE TITLE
Support messages coming in via logMessages

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#194]
Parent issue: #140 

Where it is received: https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#3294

Where it comes from: https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/webconsole.js#1418

Current test: https://dxr.mozilla.org/mozilla-central/source/devtools/shared/webconsole/test/test_nsiconsolemessage.html

Any work on this should include cached log messages as well.

**Comment by rickychien** [comment]
I'm trying to work this out and any help would be appreciated.

**Comment by linclark** [comment]
@rickychien thanks for the offer to help. This one is not currently high priority. Would you be interested in #244 instead?

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307895](https://bugzilla.mozilla.org/show_bug.cgi?id=1307895)
