### ISSUE TITLE
Support network event update messages

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#196]
Parent issue: #140 

Where it is received: https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#3348

Where it comes from: 10 different places, starting here https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/webconsole.js#2064

**Comment by rickychien** [comment]
@linclark yes, I told Honza and promised that I'm going to fix network message related issues. Please set assignee to me thanks!

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307892](https://bugzilla.mozilla.org/show_bug.cgi?id=1307892)
