### ISSUE TITLE
Support file activity messages

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#197]
Parent issue: #140 

Where it is received: https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#3364

Where it comes from: https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/webconsole.js#1599

Current test: https://dxr.mozilla.org/mozilla-central/source/devtools/shared/webconsole/test/test_file_uri.html

**Comment by bgrins** [comment]
Originator of the packet: https://dxr.mozilla.org/mozilla-central/source/devtools/shared/webconsole/network-monitor.js#1868

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307890](https://bugzilla.mozilla.org/show_bug.cgi?id=1307890)
