### ISSUE TITLE
Support private context exited messages

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#200]
Parent issue: #140 

Where it is received: https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#3402

Where it comes from: https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/webconsole.js#1740

Current test: ?

**Comment by bgrins** [comment]
Private messages are deleted in the browser console when a private window is closed.  There's an attribute set on messages here: https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/console-output.js#944-946.

In the case of page errors, 'private' appears to come through on the packet: https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1472-1484.

On console api messages, 'private' should also be part of the packet: https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1263

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307928](https://bugzilla.mozilla.org/show_bug.cgi?id=1307928)
