### ISSUE TITLE
Consider removing classes around things like console.trace()

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#202]
In the current console, we do things like

```
<span class="cm-variable">console</span>.<span class="cm-property">trace</span>()
```

Would it make sense to just have this (and others like it such as console.table) as a string? I believe that's what Chrome is doing (though I haven't checked their source for this).

This would make for simpler code paths.

@bgrins what do you think?

**Comment by bgrins** [comment]
I don't feel really strongly about it.  If it simplifies things I'd be alright with it

**Comment by nchevobbe** [comment]
I kinda like it like this
As a plain string it feels a little dull
Maybe we could have a special class for "titles" ( console.trace(), console.table(), console.group()'s label ... ) ?

**Comment by bgrins** [comment]
In the immediate term we could wrap it all in the blue `cm-variable` class

**Comment by linclark** [comment]
That suggestion works for me. I'm going to go ahead and do this in #150.
