### ISSUE TITLE
Add support for console.time()

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#207]
Add support for console.time() and console.timeEnd()

I'm working on it right now

**Comment by nchevobbe** [comment]
I was curious to see what the code below output in the current console :  

```
console.time();
console.timeEnd();
```

-> We don't show anything.
In Chrome, they output : 
`default: 2544.671ms`

I think it might make sense to have this too in our console. I think this might require some change server side, because in the code above, the message packet does not have the `timer` object at all.

---

Another test I ran was : 
`console.timeEnd("foo");`
i.e. , a timeEnd() call without a prior time() call, and if in Firefox it does not show anything, in Chrome it awkwardly show a duration (of what ? I don't know)

Maybe for this case we could output a message saying that prior time() call was not found allowing the user to know what's happening if they made a typo ?

**Comment by linclark** [comment]
This will land in m-c in [Bug 1295347](https://bugzilla.mozilla.org/show_bug.cgi?id=1295347)
