### ISSUE TITLE
Handle tip-of-tree version of Chrome protocol

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#217]
There is a stable version of the Chrome protocol and a tip-of-tree version.

`ConsoleMessage.parameters` have been [removed](https://github.com/ChromeDevTools/debugger-protocol-viewer/commit/acf8056789f0e1345fe9536f74f8a0a7ee174bbd#diff-22e7f1ed0925fad850e74056f3490040L1990) from tot and `ConsoleMessage.messageText` has been changed to `text`.

The 2nd change isn't too much of an issue, but the first change has ramifications for our use of reps. If the server is not providing the RemoteObjects, then there's no need for something like reps on the client side.

**Comment by jsnajdr** [comment]
Does that mean that if I `console.log("hello", {prop:"world"})`, the object argument cannot be expanded and inspected in the console any more? Is there only a stringified representation now?

**Comment by linclark** [comment]
After looking at it more closely, it seems that the Console domain has been deprecated and split into two. Console api messages are now in the [Runtime domain](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#event-consoleAPICalled). Other messages are handled by the [Log domain](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Log/#type-LogEntry).

The `consoleAPICalled` event has an `args` array (which was `parameters` on `ConsoleMessage`), and this contains `RemoteObjects`, which are like our grips.

However, the `LogEntry` does not seem to return any `RemoteObjects`. I'm not sure how Chrome's code will prepare `text` value for those. We'd need to dig into the code to determine.

**Comment by jsnajdr** [comment]
Do the Console API calls (log, error, trace, ...) end up also in the Log domain, or just in the Runtime's `consoleAPIcalled`? To implement a full console client, you may need to listen for events from both sources. Some are just text messages, some have rich structure.

**Comment by linclark** [comment]
In the previous version of the protocol, `console-api` was a source. If you look at the sources list in `LogEntry`, you'll see that there isn't a `console-api` listed in that enum anymore.

**Comment by jsnajdr** [comment]
That supports the conjecture that you need to setup a `consoleAPIcalled` listener to see `console-api` messages and that they are not sent to the Log Domain at all.

The `LogEntry` structure is now simple enough to be easily forwarded to any other logging infrastructure - logstash/Kibana, Java logging APIs, syslog etc. Maybe easier interoperability is the reason for this change.

The Console API can throw arbitrarily complex structures at the consumer - Javascript objects, tables, nested messages from `console.group` etc. Much harder to handle that.

**Comment by linclark** [comment]
I looked into it more. It may be that console API calls and evaluation results are the only thing we need grips for. Chrome's RDP was already handling evaluation results outside of the Console domain anyway, in the Runtime domain.

If those are the only two message types that we really needs grips for, then this change doesn't pose a problem. We'll need to move around some properties and create some new types, but there wouldn't be any place where Chrome's RDP doesn't give us the objects that we need.

That said, this is not a super high priority issue for us. I'd say we should possibly add it to the sprint after next.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307924](https://bugzilla.mozilla.org/show_bug.cgi?id=1307924)
