### ISSUE TITLE
Update text filtering and expand text filter tests

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#220]
- Additional cases in browser_webconsole_live_filtering_on_search_strings.js
- Ensure that search works against location as well, as in browser_webconsole_log_file_filter.js

**Comment by linclark** [comment]
This is weird...

```
  setStringFilter(hud, "ht tp");
  isnot(countMessageNodes(hud), 0, "the log nodes are not hidden when the " +
    "search string is set to \"ht tp\"");
```

So if you log a URL, it will match it even if the search string is `ht tp`... is this functionality we need to keep, @bgrins? Chrome doesn't seem to.

**Comment by bgrins** [comment]
> So if you log a URL, it will match it even if the search string is ht tp... is this functionality we need to keep, @bgrins?

No, let's not keep that behavior.  We can come up with and add in whatever kind of special search syntax we want later on but let's keep it simple for now

**Comment by linclark** [comment]
This will land in m-c in [Bug 1302515](https://bugzilla.mozilla.org/show_bug.cgi?id=1302515)
