### ISSUE TITLE
Show feedback for invalid consoleApi calls

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#223]
We could notify the user something is wrong when he does an incorrect call : 
- `console.timeEnd("unmatched");`
- `console.groupEnd("unmatched");`
- `console.table(notAnArrayNorObject);`

Displaying a message like `There wasn't a prior console.time("unmatched") call`, `console.table should have an object or an array as argument`, ... , maybe with the link to the MDN page of the console ? 

@helenvholmes what do you think about this ?

**Comment by bgrins** [comment]
FYI some similar things are being discussed in the spec, like https://github.com/whatwg/console/issues/60.  I haven't seen any discussion around timeEnd and groupEnd without a matching start but that's an interesting issue.

Also with console.table some differences between FF / chrome has been noted here: https://github.com/whatwg/console/blob/master/NOTES.md#consoletable---printing-of-strings, and the table logic is meant to be specified here: https://github.com/whatwg/console/issues/21.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307921](https://bugzilla.mozilla.org/show_bug.cgi?id=1307921)
