### ISSUE TITLE
Decrement repeat ID when log messages are pruned

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#228]
I'm not sure that we actually want to do this, but it looks like it is functionality that [we test for](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/test/browser_webconsole_bug_642108_pruneTest.js#72) in the current console.

I'm tempted to say we don't need this. To support it we would need to introduce much more complicated logic in the reducer.

@bgrins what do you think?

**Comment by bgrins** [comment]
Yeah, that's quite an edge case that the pruned messages change the number of repeats.  My initial thought is that it's actually better behavior if the number of repeated messages doesn't change

**Comment by linclark** [comment]
👍
