### ISSUE TITLE
Test print()

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#232]
A test for print should be added to test_commands_other.html.

<del>Currently tests like browser_webconsole_output_01.js check that print outputs different strings from console.log sometimes. Before we implement similar tests, we should make sure this feature is working how we want it to. Chrome seems to be showing a print dialog in these cases. I honestly have never used print before. @bgrins Do you have an opinion on how print should work?</del>

**Comment by linclark** [comment]
Looks like this is in the [WHATWG spec](https://console.spec.whatwg.org/#nodejs-printer). However, our implementation doesn't seem to match that, either.

**Comment by bgrins** [comment]
`print` is a command line helper only (so not exposed to web content): https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/utils/webconsole-utils.js#909-919.  I believe the code in the spec is a reference implementation and also not exposed to the web.

It's won't take any work to keep `print` working in jsterm as-is, so I'd say let's keep it and revisit if we want to remove the code later on.  For a test, we don't need to use the existing integration tests - the command could be easily tested directly in test_commands_other.html

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307916](https://bugzilla.mozilla.org/show_bug.cgi?id=1307916)
