### ISSUE TITLE
Convert browser_webconsole_output_0*.js tests to mocha

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#233]
For many of these, new stubs will need to be added.

The current tests have an object with the following keys:
- input: this is passed into console.log()
- output (or consoleOutput): this is the expected output
- printOutput: this will be handled in #232 
- inspectable: whether you can click on it for variables view
- variablesViewLabel: the label for the collapsible that represents the object in variables view. We don't currently implement this. @bgrins, do you think that we should? I'd say we don't need to since vview is just a short term solution for us.
- supressClick: I'm not actually sure why this is here. It's not documented and there are only [4 test cases](https://dxr.mozilla.org/mozilla-central/search?q=suppressClick&redirect=false) that use it, all in the same test. I wonder if it's similar to noClick? @bgrins any ideas?
- noClick: ignore

We will need stubs for these test cases. We may need to reconsider how we organize snippets. For now, let's just have all of these in their own snippet file.

**Comment by bgrins** [comment]
> variablesViewLabel: the label for the collapsible that represents the object in variables view. We don't currently implement this. @bgrins, do you think that we should? I'd say we don't need to since vview is just a short term solution for us.

I don't think we need to port this over

**Comment by bgrins** [comment]
> supressClick: I'm not actually sure why this is here. It's not documented and there are only 4 test cases that use it, all in the same test. I wonder if it's similar to noClick? @bgrins any ideas?

Here's the reason: https://bugzilla.mozilla.org/show_bug.cgi?id=1132501#c95 (which landed here: https://hg.mozilla.org/mozilla-central/rev/256e3e81fed7). Basically, clicking those functions will cause the debugger to open, so it's not there to assert anything in particular, just to make the test faster / less intermittent.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307915](https://bugzilla.mozilla.org/show_bug.cgi?id=1307915)
