### ISSUE TITLE
Clear all messages data in state when clearing messagesById

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#241]
In the messages reducer, when we deal with the `MESSAGE_CLEAR` action, we only reset the `messagesById` property :

```
case constants.MESSAGES_CLEAR:
  return state.set("messagesById", Immutable.List());
```

We should also take care of the `messagesUiById` property since the message itself does not exists anymore.

@linclark , could you assign this to me please ?

**Comment by linclark** [comment]
Good catch!

**Comment by nchevobbe** [comment]
Updated the title of this to take care of the same thing for `console.clear` calls
