### ISSUE TITLE
Implement custom styles

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#242]
In the current webconsole, you can add your own styling to console log messages.

```
console.log('%ccustom styles', 'color:green')
```

We need to reimplement this.

Tests:
- [ ] browser_webconsole_console_custom_styles.js

**Comment by linclark** [comment]
We should also test that computed styles don't break text search.

**Comment by nchevobbe** [comment]
I'll work on this after the console.group is added since I have a bugzilla bug assigned for this ( https://bugzilla.mozilla.org/show_bug.cgi?id=1088900 )

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307908](https://bugzilla.mozilla.org/show_bug.cgi?id=1307908)
