### ISSUE TITLE
Add support for console.assert()

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#244]
Tests:
- [ ] browser_webconsole_assert.js

**Comment by rickychien** [comment]
@linclark 

Where is the entry point for console.assert() when first getting started? thanks!

And is this console-fronted branch support artifact builds? Tried ./mach build many times but always get build failure.

**Comment by bgrins** [comment]
> And is this console-fronted branch support artifact builds? Tried ./mach build many times but always get build failure.

The build system should be the exact same as m-c.  I've had intermittent issues with artifact builds in general so haven't switched to them - maybe if you clobber and try again it will work?  Or we might need to rebase from the latest revs on m-c if there's an issue with the build system.

**Comment by bgrins** [comment]
> Where is the entry point for console.assert() when first getting started? thanks!

I believe the message is already routed through to the console API call at an error level: https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/new-console-output/components/message-types/console-api-call.js and https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/new-console-output/utils/messages.js#L190. 

In a quick test it seems like these messages are already showing up in the UI

**Comment by rickychien** [comment]
After asking on IRC, they confirmed that artifact builds doesn't support git. Only mercurial or git-cinnabar work well.

**Comment by rickychien** [comment]
I noticed that console.assert() works as expected, so I'm going to ensure there is a test case for it.
And we'll have a similar error message to chrome, see https://developers.google.com/web/tools/chrome-devtools/debug/console/console-reference#assert

**Comment by rickychien** [comment]
Support Assertion failed text with Rep

<img width="834" alt="screen shot 2016-08-31 at 6 08 53 pm" src="https://cloud.githubusercontent.com/assets/958165/18124710/02e1786e-6fa6-11e6-91da-d77bc5645b98.png">

<img width="841" alt="screen shot 2016-08-31 at 5 27 56 pm" src="https://cloud.githubusercontent.com/assets/958165/18123431/6236c6b2-6fa0-11e6-93c7-efc5a281148d.png">

@linclark Does the text "Assertion failed" with white color look ok?

**Comment by linclark** [comment]
@rickychien that looks good to me in the dark theme, but I wonder what it looks like in the light theme. We can check that later and change it if necessary though

**Comment by rickychien** [comment]
Update white theme and dark theme pictures. It seems that color is fine, I'm going to make sure that there is a test case for it.

**Comment by linclark** [comment]
That sounds great. If you haven't run the mocha tests before, you can find instructions in the README (which is also shown on this repo's landing page)

**Comment by rickychien** [comment]
ConsoleAPICall component threw errors 

```
TypeError: l10n.getFormatStr is not a function
```

I fixed it by a simple workaround that copy stub `getStr()` to a new `getFormatStr()` at devtools/client/webconsole/new-console-output/test/fixtures/L10n.js

I don't look at this for how to make complete `getFormatStr()` stub but it works now.

**Comment by jsnajdr** [comment]
@rickychien Julian Descottes (:jdescottes) did some changes to the L10N code recently (in mozilla-central). He will know what's the right fix to the l10n errors.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1300057](https://bugzilla.mozilla.org/show_bug.cgi?id=1300057)

**Comment by rickychien** [comment]
Cool! thanks
