### ISSUE TITLE
Flip the new frontend pref to false in the current webconsole head.js

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#245]
This way we can keep running the current tests even when we pref the new UI on in nightly

**Comment by linclark** [comment]
In our convo about this we talked about possibly copying over some mochitests that are passing. @bgrins are you ok with me doing this? It would mean that we would have to ask any contributor who updated tests to copy the change to new console in the same patch (until we pref on the console for good)

**Comment by bgrins** [comment]
I'm OK with it in general, but maybe we should try it out with a single test or two first since that might hit a lot of the issues and prevent having to duplicate as many changes.

**Comment by bgrins** [comment]
For instance, we have bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1298230 and https://bugzilla.mozilla.org/show_bug.cgi?id=1298225 currently in flight that might require duplicate changes (haven't checked each test against the doc but I suspect there will be at least some overlap)

**Comment by bgrins** [comment]
Going to handle this in the bug for turning it on: https://bugzilla.mozilla.org/show_bug.cgi?id=1304178
