### ISSUE TITLE
Add store test for MESSAGES_CLEAR action

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#249]
We do not have a test for `MESSAGES_CLEAR` action, which is fired when will-navigate is called IIUC.

We should make sure that everything in the `messages` state property is reset to their original values.

**Comment by linclark** [comment]
@nchevobbe I think we do have a test, but it wasn't updated for the messages UI stuff. Is [this](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/new-console-output/test/store/messages.test.js#69) not testing in the way you expect?

**Comment by nchevobbe** [comment]
@linclark no, I don't think so. The test you linked to only take care of `console.clear` calls. I was talking about `messageClear` action, which is called when the page navigate, and when we click on the trash icon in the filter bar. 
We do have an action test in the latter case, but we don't check the store for this action.

I pushed a PR (https://github.com/devtools-html/gecko-dev/pull/250) which does that.

**Comment by nchevobbe** [comment]
Closed #241 via #250.
