### ISSUE TITLE
Change how navigation markers look

### ISSUE THREAD

**Issue by nt1m** [firefox-devtools/original-console-fork#254]
I think they should clearly separate different navigation sessions, we could use a thick separator before the "navigated to" message

**Comment by linclark** [comment]
Thanks for the suggestion. We have made the product decision to match Chrome for this (and many other features). This means that instead of having a navigation marker as we currently have it, there is instead a message that says `Navigated to <url>`.

**Comment by nt1m** [comment]
@linclark Was this fixed?
I'm actually fine with showing Navigated to <website> like chrome, but it would be nice to have a better visual separation, eg. when you scroll the output quickly, you should be able to spot the message
