### ISSUE TITLE
Entering a command should automatically scroll the output to the bottom

### ISSUE THREAD

**Issue by nt1m** [firefox-devtools/original-console-fork#255]
When you run a command, the console output should automatically scroll to where the command is displayed (to the bottom)

**Comment by linclark** [comment]
Agreed.

Steps to reproduce:
1. fill the console until the scroll appears
2. scroll to the top
3. press the up key so that you can run your command again and press enter

Expected result: the console scrolls to the bottom
Actual result: the console stays at the current scroll position

**Comment by linclark** [comment]
This will land in m-c in [Bug 1306099](https://bugzilla.mozilla.org/show_bug.cgi?id=1306099)
