### ISSUE TITLE
Support mixed content for network event messages

### ISSUE THREAD

**Issue by rickychien** [firefox-devtools/original-console-fork#265]
Parent issue: #140

There is an existed bug when showing mixed content for network log. AFAIK, mixed content warning only appear in:
https://people.mozilla.org/%7Etvyas/mixedboth.html
but doesn't appear in:
https://googlesamples.github.io/web-fundamentals/samples/fundamentals/security/prevent-mixed-content/simple-example.html

We should make sure warning message display properly on both of above websites

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307903](https://bugzilla.mozilla.org/show_bug.cgi?id=1307903)
