### ISSUE TITLE
Don't show resource URIs in stacktrace

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#266]
When `console.trace()` is called directly in the console, it shows the resource URIs for the actors.

**Comment by bgrins** [comment]
Odd that this is unique to the new frontend.  It seems like a backend issue if it's including resource URIs in the trace

**Comment by linclark** [comment]
Yeah, that has me confused too. I'm assuming it's one of the following: 1) the new console gets the wrong property from the packet, or 2) there's some code in old console which cleans up the stacktrace. Still need to look into it though

**Comment by nchevobbe** [comment]
I can have a look and see what's wrong

**Comment by nchevobbe** [comment]
![screenshot at sept 13 21-00-34](https://cloud.githubusercontent.com/assets/578107/18487350/24f7c058-79f5-11e6-8518-6424ace0c20e.png)

@linclark Do you talk about that ? Because I see it too in the old console. We could still have a look and remove it from the stack in `utils/message.js`'s `transformPacket`

**Comment by bgrins** [comment]
> @linclark Do you talk about that ? Because I see it too in the old console. We could still have a look and remove it from the stack in utils/message.js's transformPacket

I'm generally OK with the "debugger eval code" source link since if you type console.trace() into the console input

**Comment by linclark** [comment]
Everything below anonymous is what I'm talking about... does it not show up for you?

<img width="1249" alt="restore_session" src="https://cloud.githubusercontent.com/assets/105464/18487748/66b71452-79c4-11e6-8d66-5c9a12d195d6.png">

**Comment by bgrins** [comment]
Oh, I see it in the browser console (old frontend) but not in the webconsole (new or old frontend)

**Comment by bgrins** [comment]
_if_ this is only an issue in browser console I'd say it's a wontfix

**Comment by linclark** [comment]
@bgrins so I see it in the webconsole with new frontend... am I the only one? Maybe this is a BT profile issue and I just opened the browser toolbox in a different order?

**Comment by linclark** [comment]
So on a rebuild, this went away. I have no idea what could have caused that. I definitely wasn't looking at the browser console.

I have seen this issue before, so will re-report it if I see it again.
