### ISSUE TITLE
Match against stacktrace in text filter

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#270]
This is currently supported in Firefox but not in Chrome. @bgrins, any opinions on whether we should support it?

I'm thinking yes, but not high priority.

**Comment by bgrins** [comment]
We should definitely support it.  Agreed it's not super high priority but it's probably also fairly easy

**Comment by linclark** [comment]
This will land in m-c in [Bug 1303101](https://bugzilla.mozilla.org/show_bug.cgi?id=1303101)
