### ISSUE TITLE
Remove quotes around strings

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#275]
In current Firefox/Chrome, `console.log("1")` will output `1`. In new frontend, we output `"1"`, but we should change this.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1302873](https://bugzilla.mozilla.org/show_bug.cgi?id=1302873)

**Comment by nchevobbe** [comment]
StringRep have a `omitQuotes` props we could use to achieve this.
