### ISSUE TITLE
Make it possible to filter network messages

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#290]
Related to #132.

Network requests are always visible at the moment. We should make it possible to turn off network messages.

**Comment by nchevobbe** [comment]
Yes, I'm gonna look into it since we now support network messages. @linclark would you assign this to me please ? Thanks

**Comment by linclark** [comment]
This will land in m-c in [Bug 1304900](https://bugzilla.mozilla.org/show_bug.cgi?id=1304900)
