### ISSUE TITLE
Make npm test work with devtools/client package.json

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#291]
Because of some interaction between npm, mocha, and babel, `npm test` doesn't work when there is a babel configuration for the package.json in devtools/client.

For now, we can just install babel at the higher level. We should eventually figure out how we want to handle multiple package.jsons, or a single package.json for all tools.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1303872](https://bugzilla.mozilla.org/show_bug.cgi?id=1303872)

**Comment by linclark** [comment]
Just fixed this with da258943b0f333e3fb2562b99874d4ca3f679cda and bcc20ee1adf9f0fd23afdd0e10f749312fe2dbc3.

@nchevobbe @rickychien, this pulls in changes from m-c, so you'll need to rebase and also run `npm install` from the webconsole directory.

**Comment by linclark** [comment]
@nchevobbe Ricky and I just figured out that you need to force npm to download the latest version of redux-mock-store... `npm install redux-mock-store@1.2.0`

**Comment by nchevobbe** [comment]
Thanks for letting me know
