### ISSUE TITLE
Add reverse search in jsterm

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#306]
It would be very nice to have a reverse search similar to what the terminals have.
I would be triggered with <kbd>Ctrl</kbd>+<kbd>R</kbd> , and would display the last matching command. 
We would then be able to navigate backward striking <kbd>Ctrl</kbd>+<kbd>R</kbd> again, or forward with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>

I think we would need to mock this out, to see what to display, and how, how this would fit with multiline commands, and probably things I'm not thinking of right now. 

What do you think about this ?

**Comment by nchevobbe** [comment]
Ugh, there's an existing bugzilla bug with more thoughts on that : https://bugzilla.mozilla.org/show_bug.cgi?id=1024913

**Comment by linclark** [comment]
Ok, I'm going to close this one out in favor of the bugzilla one. We will likely be using a different system—either going back to Bugzilla, or using GitHub but not in a gecko-dev fork—after we finish work on phase 1.
