### ISSUE TITLE
Better navigation through history with multiline commands in jsterm

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#307]
One thing I find annoying is navigating through the history ( with the <kbd>↑</kbd> key ) when I have multiple lines command. 
This is because when going through the history, the cursor gets placed in the last line, and only navigate to the previous entry when the cursor is on the first line ( or in the last line if we want to navigate with the <kbd>↓</kbd> key ). 

We could have a shortcut like <kbd>Maj</kbd> +  <kbd>↑</kbd> and <kbd>Maj</kbd>&nbsp;+&nbsp;<kbd>↓</kbd>) to automatically jump to the previous/next entry, wherever the cursor is.

**Comment by bgrins** [comment]
Note: you can do cmd+up/down (or ctrl+up/down) which isn't quite what you want but limits the number of presses (it will skip straight to the beginning / end on the first press then continue navigating on the next).

I'm not sure if there is a meta key that we can use that wouldn't end up overriding some system behavior.  Maybe we could use alt, although at least on OSX it does modify the cursor navigation by default (first press moves cursor to beginning or end of the line, then the next moves up / down lines)

**Comment by bgrins** [comment]
Also relevant would be reverse-search through command history: https://bugzilla.mozilla.org/show_bug.cgi?id=1024913

**Comment by nchevobbe** [comment]
I didn't know about cmd+up, thanks !

**Comment by linclark** [comment]
I'm going to close this one out since we will likely have switched to a different bug tracking system by the time we would work on this.
