### ISSUE TITLE
Get cached network messages

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#311]
As discussed in #305, the cached network messages aren't being delivered to the new console frontend. This probably means that we are missing a listener or something.

**Comment by linclark** [comment]
@rickychien If you're looking for other issues, this is another high priority one.

**Comment by rickychien** [comment]
@linclark thank you for doing this :)

I think it's time to focus back on inspector de-chrome work from now but I'll back to here again and keep contributing in new webconsole front-end in my spare time.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307948](https://bugzilla.mozilla.org/show_bug.cgi?id=1307948)
