### ISSUE TITLE
Small UX nit: expanding messages may drop you to the bottom 

### ISSUE THREAD

**Issue by jlongster** [firefox-devtools/original-console-fork#315]
This only happens if you haven't reached the bottom of the screen yet (I think?). If I have a few messages, with one that has expandable data, like this:

<img width="483" alt="screen shot 2016-09-27 at 11 58 22 am" src="https://cloud.githubusercontent.com/assets/17031/18881575/ddfd68e6-84a9-11e6-81df-1b5d3a74ac2f.png">

If I expand it, and it's really long, it drops me to the bottom of the expanded output:

<img width="482" alt="screen shot 2016-09-27 at 11 58 33 am" src="https://cloud.githubusercontent.com/assets/17031/18881579/dfecfb44-84a9-11e6-88fb-7947bf45ba33.png">

Here's the previous console behavior:

<img width="540" alt="screen shot 2016-09-27 at 11 58 46 am" src="https://cloud.githubusercontent.com/assets/17031/18881632/0c6b9fe0-84aa-11e6-8c21-3e432203eb38.png">

<img width="565" alt="screen shot 2016-09-27 at 11 58 55 am" src="https://cloud.githubusercontent.com/assets/17031/18881637/0ecf6758-84aa-11e6-99b9-cdeea0c64a29.png">

**Comment by linclark** [comment]
@jlongster thanks for filing :) There couple a few issues with the current scroll, so I put up a PR that should fix them.
