### ISSUE TITLE
Long strings are unnecessarily truncated

### ISSUE THREAD

**Issue by jlongster** [firefox-devtools/original-console-fork#316]
This is a warning that is printed to the old console:

"Warning: Factory.type is deprecated. Access the class directly before passing it to createFactory."

In the new console, it only shows:

"Warning: Factory.type is ...ing it to createFactory."

It truncates it but I don't think strings in the console should be truncated unless they are extremely long (like maybe 2000 chars or something?)

**Comment by linclark** [comment]
I believe this should be fixed by [Bug 1304804](https://bugzilla.mozilla.org/show_bug.cgi?id=1304804). Let me know if that doesn't fix it for you.

**Comment by jlongster** [comment]
I bet it will; I don't have an up-to-build to apply a patch on right now (need to clobber build) but feel free to dupe this to that. It definitely seems like the same thing.

**Comment by linclark** [comment]
Cool, thanks for pointing it out.

**Comment by jlongster** [comment]
@bgrins can verify by just doing `console.warn("Warning: Factory.type is deprecated. Access the class directly before passing it to createFactory")` and making sure it's not truncated with his patch.

**Comment by bgrins** [comment]
Yes, Bug 1304804 will fix that (currently landed on autoland repo)
