### ISSUE TITLE
css links do not open the style editor

### ISSUE THREAD

**Issue by tromey** [firefox-devtools/original-console-fork#317]
I've found that clicking on a CSS link in the console does not open the style editor.  Instead it tries to open the debugger, which doesn't know about the file, so nothing is shown.

STR:
- Open http://wordpress.com/
- Open the console
- Click on one of the CSS links.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307944](https://bugzilla.mozilla.org/show_bug.cgi?id=1307944)
