### ISSUE TITLE
Add support for logging objects

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#32]
Currently, console.log() only works for strings. If you try to log an object like window, nothing shows up.

**Comment by linclark** [comment]
I did not mean to close this, but apparently saying "fix #N" in a comment on the PR will close things now.

**Comment by nchevobbe** [comment]
@linclark , I think you have one of this in mind for me. Could you mention me when you create an issue I can work on ? Thanks !

**Comment by linclark** [comment]
@nchevobbe I had been thinking this was a good bug, but I realized we might do this differently based on #43. I filed another one that would be good earlier today, though. I'll be sure to add mentions as I go along, thanks for the suggestion :)

**Comment by linclark** [comment]
This will be fixed by #94
