### ISSUE TITLE
DOM nodes aren't being highlighted in the page on hover

### ISSUE THREAD

**Issue by captainbrosset** [firefox-devtools/original-console-fork#321]
I searched github and bugzilla for this and couldn't find a relevant issue, so filing here:

STR:
- Open the console
- Enter `document.body`
- Hover over the output HTMLBodyElement

Expected: the <body> node should become highlighted in the page.
Actual: nothing happens.

**Comment by linclark** [comment]
Thanks for filing. I haven't looked into it, but I bet this will be an easy fix.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307941](https://bugzilla.mozilla.org/show_bug.cgi?id=1307941)
