### ISSUE TITLE
There's no icon next to DOMNodes to select them in the inspector

### ISSUE THREAD

**Issue by captainbrosset** [firefox-devtools/original-console-fork#322]
Similar to #321 : 

STR:
- Open the console
- Enter `document.body`

Expected: next to the HTMLBodyElement output, there should be a little inspector icon.
Hovering over this icon should display a tooltip: "Click to select the node in the inspector".
Clicking on this icon should switch to the inspector panel and select the body element.

Actual: nothing happens.

**Comment by linclark** [comment]
IIRC, this icon is available when DOM nodes are shown in some of the other tools as well. @captainbrosset Is that correct, or if it isn't, should they be? 

If so, I think we want to handle it in a Rep. If not, we could likely add it in the `GripMessageBody`

**Comment by captainbrosset** [comment]
Yes we should handle this in the Rep, since it would be nice to have this icon in all tools that show DOM node previews. We do this at the moment in the variable-view, the animation-inspector, and obviously the console.
On the long run, it'd be nice for the markup-view to also use Reps to display the DOM tree, but there, we won't need the icon, so maybe the Rep should have accept an option that controls whether the icon is shown or not.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307940](https://bugzilla.mozilla.org/show_bug.cgi?id=1307940)
