### ISSUE TITLE
TextNodes should also support highlight on hover

### ISSUE THREAD

**Issue by captainbrosset** [firefox-devtools/original-console-fork#323]
#321 is about adding highlight on hover to DOMElements in the console.

This issue is about doing the same for TextNodes.

As of this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1304679 we're able to highlight text nodes in Firefox DevTools, and it's very useful in some cases where text nodes have a different geometry than their parent element.
So, as you move your mouse over a text node in the console output, it'd be great if we could simply highlight it in the page.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307939](https://bugzilla.mozilla.org/show_bug.cgi?id=1307939)
