### ISSUE TITLE
Performance issue when logging in a loop

### ISSUE THREAD

**Issue by captainbrosset** [firefox-devtools/original-console-fork#324]
STR:
- open the console
- enter `for (let i = 0; i < 2000; i++) console.log("test log", i);`

With the old console front-end, I get an immediate result, I see the 2000 logs being output quickly in the console.
With the new front-end, the whole toolbox freezes, and in fact maybe the whole browser. I can't select another tab, clicks in the content page have no effects, I can't select another tool in the toolbox, and the console doesn't display the 2000 logs.

If I wait for, I don't know, maybe a minute or so, the output appears, and the browser becomes responsive again (in fact, all of the clicks that I had made while the browser was stuck are all processed at once).

I ran a few tests, on my desktop PC (windows 10, intel i7, 3.6GHz, 32GB of RAM):
- if the loop iterates 500 times, it takes roughly 20 seconds
- if the loop iterates 100 times, it takes about 2 seconds

**Comment by linclark** [comment]
Thanks for filing this. This issue was touched upon in #309, but we didn't have an issue for tracking it.

The reason for this is that we are doing a dispatch on each message. We can easily batch those dispatches for cached messages, but it's harder to do when the messages are coming in via separate events.

@bgrins we should probably revisit the throttling and see which tests were failing. We might be able to make those tests pass by using a `waitFor` approach.

**Comment by linclark** [comment]
Another option would be to throttle from inside `messageAdd`. We could collect an array of prepared messages as they come through and only dispatch that (as a batch) every 50ms or so.

**Comment by bgrins** [comment]
This sort of problem is being picked up by damp in try runs (in console.bulklog): https://treeherder.mozilla.org/perf.html#/comparesubtest?originalProject=try&originalRevision=ff39f20979ea&newProject=try&newRevision=333bcbacf930&originalSignature=2443f35ea4dcddc22273f07bad4be47e2d43d4a0&newSignature=2443f35ea4dcddc22273f07bad4be47e2d43d4a0&framework=1.

We should try throttling and see if that can get us near parity with the old frontend

**Comment by linclark** [comment]
Just to capture an idea that we were spitballing over IRC:

We could move firing the "new-message" event to `componentDidMount`. This should ensure that tests don't fail when we throttle.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1306783](https://bugzilla.mozilla.org/show_bug.cgi?id=1306783)
