### ISSUE TITLE
Display DOMNodes in a more user friendly way (i.e. not HTMLBodyElement but <body>)

### ISSUE THREAD

**Issue by captainbrosset** [firefox-devtools/original-console-fork#325]
I'm fairly certain this got discussed at some stage either in a bug or on IRC, but after talking to @nchevobbe he said that didn't ring a bell to him, so I'm filing this just in case.

The old front-end used to display DOMNodes in a way that makes more sense to users, it used to preview them in 2 ways:
- compact: `<tag#id.class>`
- HTML: `<tag id="id" class="class">`

Right now, they get displayed as HTMLTagElement.

**Comment by linclark** [comment]
> I'm fairly certain this got discussed at some stage either in a bug or on IRC

I agree, I think there is an issue in Reps for this. But I can't find it at the moment, so I'm going to leave this one open.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307938](https://bugzilla.mozilla.org/show_bug.cgi?id=1307938)
