### ISSUE TITLE
Add support for console.clear()

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#33]
This is being added to the current frontend in https://bugzilla.mozilla.org/show_bug.cgi?id=659625

**Comment by bgrins** [comment]
We'll need to rebase on upstream to get the platform support

**Comment by linclark** [comment]
What would you think of landing something before we rebase (and doing that soon)? I'm thinking it might be good to get it in early so that we can have it reviewed by others in chunks.
Like maybe we could land a patch with all the updates every other week?

**Comment by bgrins** [comment]
I'm not against that at all and I think it's a good idea to avoid code drift and be able to show off our progress. We'll need to do a few things:
- Rename anything that has an obviously temporary name
- Create an actual pref to enable the frontend
- Make sure all existing tests pass
- Find a reviewer (or do we need an additional reviewer since we've been reviewing each other's PRs?)
- Anything else?

**Comment by linclark** [comment]
I think that just about covers it. I created a meta issue and milestone to track it.

**Comment by nchevobbe** [comment]
@bgrins , I think Lin rebased console-frontend branch yesterday, so we have the console.clear change. I was thinking of working on this issue, is it okay for you ? Or do you prefer me to work on another one ?

**Comment by bgrins** [comment]
> I think Lin rebased console-frontend branch yesterday, so we have the console.clear change. I was thinking of working on this issue, is it okay for you ? Or do you prefer me to work on another one ?

Yeah working on this one sounds good

**Comment by bgrins** [comment]
Fixed by #82
