### ISSUE TITLE
Reset filter prefs in between tests

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#332]
Right now we don't clean up filtering after browser_webconsole_filters.js finishes, so the error filter is off for the rest of the tests.  This'll eventually cause a problem, so we should make sure to reset it in a cleanup function in our head.js file

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307936](https://bugzilla.mozilla.org/show_bug.cgi?id=1307936)
