### ISSUE TITLE
Can't copy output with ctrl+C

### ISSUE THREAD

**Issue by captainbrosset** [firefox-devtools/original-console-fork#335]
STR:
- Output anything in the console, in my case I just had a bunch of strings
- Select the output text with the mouse
- Press ctrl+C (I'm on windows, haven't tested on Mac)

Expected: the text is now in my clipboard and can paste it somewhere
Actual: the test was not copied to my clipboard

There's also a contextmenu "copy" option, but I coudn't get it enabled. Even when right-clicking on the selected text, the "copy" option remains disabled.

**Comment by linclark** [comment]
Thanks for filing. This may be related to #224, but I'm going to leave it open until that has landed. We plan to land that before turning on in Nightly.

**Comment by linclark** [comment]
And the context menu issue is #284. That is also in the "fix before turning on in Nightly" list

**Comment by linclark** [comment]
This was fixed with [Bug 1307198](https://bugzilla.mozilla.org/show_bug.cgi?id=1307198).
