### ISSUE TITLE
Failure in "filters network messages" test

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#349]
STR : 
1. `npm test` 

I don't know what causes this yet

**Comment by linclark** [comment]
shoot, this is probably due to the batching added in #344

**Comment by linclark** [comment]
If it is, it's probably not actually broken. It's just that it delays the dispatch of `messageAdd`, which means it introduces the possibility for intermittents.

**Comment by linclark** [comment]
@nchevobbe actually, this does fail for me when I have your branch for #339 checked out, but not on console-frontend. Can you check on your machine? It could still be an intermittent, but that makes me wonder whether there isn't an issue being introduced in that branch.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307930](https://bugzilla.mozilla.org/show_bug.cgi?id=1307930)
