### ISSUE TITLE
Warning symbol should be red (or yellow) and not greyish

### ISSUE THREAD

**Issue by jnachtigall** [firefox-devtools/original-console-fork#351]
Previously the warning had a red warning symbol now it's just greyish and easy to overlook. See https://bug1306274.bmoattachments.org/attachment.cgi?id=8796138 and compare with the current at https://bug1306274.bmoattachments.org/attachment.cgi?id=8796443

(Distilled this bug report from from the comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1306274#c2)

**Comment by nchevobbe** [comment]
Thanks for reporting, I'll have a look at this

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307888](https://bugzilla.mozilla.org/show_bug.cgi?id=1307888)
