### ISSUE TITLE
console.log() calls break any message afterwards

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#36]
Now that evaluation results are handled, the return from a console.log is being piped through the `EvaluationResult` component. However, that component only knows how to handle dates. This means it errors out when console.log() returns the evaluation result of `undefined`. Should be easy enough to fix... just need to implement the component to handle it.

**Comment by bgrins** [comment]
What do you think about adding a fallback renderer for generic objects without a known renderer?  This'll fix other similar issues in the mean time, and we might need one anyway for plain objects / objects with a custom type

**Comment by linclark** [comment]
Yeah, I had that thought in the back of my mind too. Sounds like a good plan.
