### ISSUE TITLE
Prototype using reps

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#43]
Honza has created [reps](https://dxr.mozilla.org/mozilla-central/search?q=path%3Areps&redirect=false&case=true) for use in other tools. We plan to integrate reps in order to [remove variables view](https://bugzilla.mozilla.org/show_bug.cgi?id=1243802).

It might be worth it to skip variables view entirely, depending on how hard it is to get the reps working for what we need. Worth prototyping at least.

**Comment by linclark** [comment]
After looking closer at reps, I think we can possibly use reps to format the top level grip **and** use variables view to inspect the lower level properties. That would probably be the best short term.

**Comment by linclark** [comment]
@nchevobbe, if you're feeling ambitious, this would be a great one. I put up a PR that provides a starting point. It uses the recently-added Reps framework to determine how to format results.

It doesn't give us exactly the output we want. For example, `console.log({})` doesn't output `Object { }` like we'd want, but instead `[ {} ]`. 

I think we might eventually need to create a `ConsoleRep` component based on `Rep` that has it's own list of registered reps... it could reuse most, but we might need our own for things like object where we want to have the word Object and link it to the variables view.

A good place to start might be to get an array of strings outputing correctly (to match the current behavior). We could address the others in other PRs.

**Comment by nchevobbe** [comment]
Sure, I'll have a look this week-end. Thanks for pointing this.

**Comment by linclark** [comment]
I just had a discussion with @janodvarko (aka Honza) about this... he's the one who created reps. I think we came up with a more elegant solution than the one I suggested above.

**Problem 1:** We need a variables view link, but other consumers of reps don't

To get around this, we could create a new optional prop on Rep called something like `titleLinkHandler`. This would take the [function that should be used for the title link](https://github.com/linclark/gecko-dev/blob/b350b110659625db4b04ddb946264b77c3b7c6ce/devtools/client/webconsole/new-console-output/components/console-output.js#L47). 

Then, Rep could pass that down. In the `getTitle()` functions on the reps, we could check for the prop. If it's available, then output the appropriate title with an onClick handler. If not, maintain the current functionality and don't output any title (for now at least, unless Honza disagrees).

**Problem 2:** We may need the output to display differently

The first example of this is the array that comes back from console log calls as arguments. You can see that in the WIP PR that I put up. We can get around this case by not passing it in as an array, but just iterating through it.

If we run into other examples where we need it to display differently, we can use the `mode` system in reps. Currently there is `long`, `small`, and `tiny`. We could introduce a `legacy` mode that outputs things as they are currently.

---

It's not 100% sure that this will all work. If you run into anything that doesn't make sense, it may be that it isn't the right solution. Let me know if you run into any stumbling blocks and we can figure out if it's a limitation of this approach.

**Comment by bgrins** [comment]
See also: https://github.com/jlongster/debugger.html/issues/132

**Comment by nchevobbe** [comment]
> To get around this, we could create a new optional prop on Rep called something like titleLinkHandler. This would take the function that should be used for the title link.
> Then, Rep could pass that down. In the getTitle() functions on the reps, we could check for the prop. If it's available, then output the appropriate title with an onClick handler. If not, maintain the current functionality and don't output any title (for now at least, unless Honza disagrees).

I think I'm on the right tracks for this. I succeed in displaying the title (Array), and showing the variable view when clicking on it. 
However, I do have an issue displaying the content of the array. It seems that  `GripArray` expect a `provider` prop (https://github.com/bgrins/gecko-dev/blob/console-frontend/devtools/client/shared/components/reps/grip-array.js#L53).
I guess this expect a GripProvider (https://github.com/bgrins/gecko-dev/blob/console-frontend/devtools/client/dom/content/grip-provider.js) but I'm not sure, as there are others places where the term provider is used. 

If it is, I have two questions : 
- What does it expect for the `dispatch` prop ? I looked on the dom-panel, it is passed from MainFrame, but we are creating it without a `dispatch` prop (https://github.com/bgrins/gecko-dev/blob/console-frontend/devtools/client/dom/content/dom-view.js#L41). But maybe it doesn't matter as we only use it if we have missing data on the actor, and it might not occurs in our case ? 
- If we should use the GripProvider, shouldn't we move it to client/shared so we can use it too from the console ?

There's another thing that we should take care of: `StringRep` displays string with quotes around them (e.g. `"test"`), though we don't want them. I guess it could be as simple as a prop on the Rep too (`displayQuotes` ?). Or should we test if the log object is a string and not use Rep at all ? 

Thanks !

**Comment by janodvarko** [comment]
> However, I do have an issue displaying the content of the array. It seems that GripArray expect a provider 

The provider is important for the the tree-view and responsible mainly for providing children when a tree-node is expanded. I think that it should be only used by the tree and not by reps reps don't need to fetch additional actors by themselves). 

There are only couple of places where the provider is used: GripArray and NamedNodeMap. I think it's save to remove it i.e. instead of:

`let value = provider.getValue(array[i]);`

it should do:
`let value = array[i]);`

And the condition checking presence of the provider can also be removed 

It should be as follows in  NamedNodeMap:

```
let item = ownProperties[name];
props.push(Object.assign({}, this.props, {
  object: item,
  equal: ": ",
  delim: ", ",
}));
```

> There's another thing that we should take care of: StringRep

Yes new prop sounds fine. Later we  can remove quotes entirely if we agree that they shouldn't appear in the UI at all.

Let me know if there is any issue with removing the provider, I can help with that.

Honza

**Comment by janodvarko** [comment]
Btw. I found a bug when looking at NamedNodeMap.

Reported:
https://bugzilla.mozilla.org/show_bug.cgi?id=1273534

Please, let me know if anyone is blocked by this and I can fix it promptly!

Honza

**Comment by nchevobbe** [comment]
Added a WIP here https://github.com/bgrins/gecko-dev/pull/85

**Comment by linclark** [comment]
Current WIP is #94
