### ISSUE TITLE
Introduce message limit

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#45]
We need to have a point at which we start pruning the message list. [Currently](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#66) it's 1000.

This should be configurable so that we can change it in tests.

**Comment by linclark** [comment]
@nchevobbe this would probably be a good one

**Comment by linclark** [comment]
@bgrins I didn't realize the console limits applied per category. Do you think this is a feature that we need to keep? Or can we change it so there is one global message limit?

**Comment by linclark** [comment]
See https://dxr.mozilla.org/mozilla-central/source/devtools/client/preferences/devtools.js#299

**Comment by bgrins** [comment]
Global message limit works for me

**Comment by nchevobbe** [comment]
okay so I'll add a `devtools.hud.loglimit` and will use it in https://github.com/devtools-html/gecko-dev/pull/100 . 
Should we have a bug to remove the category limit prefs when we'll switch to the new console ?

**Comment by linclark** [comment]
> Should we have a bug to remove the category limit prefs when we'll switch to the new console ? 

I was thinking the same thing. I'll create a bug to catch all of this cleanup work that needs to happen

**Comment by linclark** [comment]
This landed in https://bugzilla.mozilla.org/show_bug.cgi?id=1285672
