### ISSUE TITLE
Add an icon component

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#52]
All of the messages have an icon to show if the message is a log, a warning, etc. You can see examples of the HTML here:
- https://github.com/linclark/webconsole-rdp/blob/master/data/pageError/ReferenceError.html
- https://github.com/linclark/webconsole-rdp/blob/master/data/evaluationResult/Date/new-Date.html

We should have a component that handles this markup.

```
<span class="icon" title="Log"></span>
```

**Comment by linclark** [comment]
@nchevobbe this is another good one

**Comment by nchevobbe** [comment]
I started working on this and got it working. Though, there would be conflicts when https://github.com/bgrins/gecko-dev/pull/64 is merged. Should I wait for the latter to be merged, or can I just add a commit for this issue on top of my existing commits, on the same branch ?

**Comment by linclark** [comment]
Sorry, I didn't see that you'd pushed up new commits to the other PR! I'll test that and get it merged. 

For this one, you can push up your branch as a PR and note that it has a dependency.
