### ISSUE TITLE
Standardize component imports: either destructure or use dot notation

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#53]
Currently some components are imported like this:

```
const { MessageRepeat } = require("../message-repeat");
...
createElement(MessageRepeat, {})
```

and others are like this:

```
const MessageContainer = createFactory(require("../message-container").MessageContainer);
...
MessageContainer({})
```

Some folks have suggested a standard across devtools... only having 1 export per component file which would look like:

```
const MessageContainer = createFactory(require("../message-container"));
...
MessageContainer({})
```

That would be fine if we had ES6 modules and could export defaults, but still have named exports for helpers. But unfortunately with CJS we can only do either a single (unnamed) export or multiple named exports.

@bgrins, what do you think of standardizing on the second. We can then transition to the third as soon as ES6 modules are available.

**Comment by bgrins** [comment]
Works for me

**Comment by linclark** [comment]
@nchevobbe this would be a good one if you're looking for another issue. We should fix this one before we land this work upstream
