### ISSUE TITLE
Rename things with obviously temporary names

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#57]
- [ ] OutputWrapperThingy
- [ ] SUPER_FRONTEND_EXPERIMENT

anything else?

**Comment by linclark** [comment]
@nchevobbe This is another good one. If we get this and the npm one done this week, we can probably land this upstream early next week.

I'd say good names are NewConsoleOutputWrapper and NEW_CONSOLE_OUTPUT_ENABLED. @bgrins, feel free to chime in if you disagree.

**Comment by nchevobbe** [comment]
Sure! I'm currently fixing the ESLint errors we have, and I'll switch to this after.
