### ISSUE TITLE
Create an actual pref to enable the frontend

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#58]
This pref should be disabled by default.

@nchevobbe, this would probably be a good one

**Comment by nchevobbe** [comment]
@linclark , should I just add the preference, or change the tests we have with SUPER_FRONTEND_EXPERIMENT ?

**Comment by linclark** [comment]
@nchevobbe The pref should be used in the conditional that determines if the SUPER_FRONTEND_EXPERIMENT boolean is set (on line 506 in webconsole.js). We have another issue to rename that boolean, which would be another good one if you want to take it on.

We will also need to add the pref to any end-to-end tests that we add, but for now we shouldn't need to add it to any tests.
