### ISSUE TITLE
Remove all npm remnants

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#60]
Originally we had been working with mocha tests and had a package.json file committed. We'll need to make sure none of that gets included with the patch.

**Comment by nchevobbe** [comment]
I did not found any mocha test. I might missing them, but there are commits that removed those tests ( https://github.com/bgrins/gecko-dev/commit/992c8b578520e44fb28a25d842a4a76231afe343 , https://github.com/bgrins/gecko-dev/commit/919b97e5f9e086da876302fc360db4f6baa8da4a, https://github.com/bgrins/gecko-dev/commit/ebaa77110af1dd7b16cca1b96962764c98152e25 ).
