### ISSUE TITLE
Use immutable data structures

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#61]
We should use Immutable.js for handling the data that comes through reducers.

**Comment by nchevobbe** [comment]
So, I had a look at Immutable.js, watched the talk about it (which was great), and successfully used it in the messages reducers. 

The only thing I did for now is to switch `function messages(state = [], action)` to `function messages(state = Immutable.List(), action` and adapted the existing code to use it.

Now I wonder if the `action` parameter should be replaced with an Immutable.Map too ?

**Comment by bgrins** [comment]
@nchevobbe is this done now with #81 or is there more to do?

**Comment by nchevobbe** [comment]
I do think so, but I'd prefer @linclark to confirm

**Comment by linclark** [comment]
Thanks for checking. The action parameter doesn't need to be immutable, so this should be finished.
