### ISSUE TITLE
Get data from the store using selectors on the reducer

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#62]
Right now, the `mapStateToProps()` function digs into the state object itself. Instead, it should call a function on the reducer.

**Comment by nchevobbe** [comment]
@linclark this sounds interesting and I'd like to work on it to learn about store and reducers. Do you think it's a good fit for me ? Thanks

**Comment by linclark** [comment]
For sure :) I haven't looked at it closely, but a good start would be putting a function on the messages reducer to get all messages. This would be used in `mapStateToProps` functions. Something like

```
function mapStateToProps(state) {
  return {
    messsages: getAllMessages(state)
  }
}
```

Then the `getAllMessages` function would just return the correct property off of the state object.
