### ISSUE TITLE
Add support for console.table()

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#65]
Packets and current HTML can be found [here](https://github.com/linclark/webconsole-rdp/tree/master/data/consoleAPICall/console-table)

As discussed with @bgrins, we will probably diverge from the current HTML on this one. Even providing a simple HTML table element would work. This will likely be handled with reps.

Integration would happen [here](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1279).

**Comment by bgrins** [comment]
We could special case console.table() for adding a `<table>` element here: https://github.com/devtools-html/gecko-dev/blob/console-frontend/devtools/client/webconsole/new-console-output/components/message-types/console-api-call.js#L29

**Comment by linclark** [comment]
Here's the [current code](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/console-output.js#1775) for table output, and here's [what Chrome does](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/console/ConsoleViewMessage.js?q=_formatParameterAsTable&sq=package:chromium&l=551&dr=C).

**Comment by nchevobbe** [comment]
I started to look at this, and I wonder how we should handle the fact that we don't directly have the object/table but just a preview.
In the current console, we asynchronously load the complete object : http://searchfox.org/mozilla-central/source/devtools/client/webconsole/console-output.js#1807 .

What I've been thinking of is something like : 
1. when adding console.table message, check if there is a `complete` (or better) props in the new Table component
2. if not, dispatch an action to retrieve the full set of data
3. when getting those data, dispatch another action ( something like data_retrieved ), which would toggle the `complete` props on the Table component
4. back to step 1, but now we have the full set of data, and we can render the data properly

Am I on the right track ?

**Comment by linclark** [comment]
That sounds like a good strategy.

Rather than a generic data received action type, I'm thinking that an action type more specific to the table might be better. If we overload the data_received action type with any other calls, we'd to react to the data_received action type in multiple reducers.

You'll probably want to put the call to the server in the `componentWillMount`. 

It's probably worth breaking out a separate component that ConsoleApiCall delegates to for this.

**Comment by linclark** [comment]
Btw, we should make sure to cover all of the test cases in browser_webconsole_output_table.js

**Comment by nchevobbe** [comment]
So, I did what I should have done in the first place and read the doc for async actions in Redux ( http://redux.js.org/docs/advanced/AsyncActions.html ). It advises to have middlewares to handle those kind of actions. I checked the new debugger and they're also using middlewares ( https://github.com/devtools-html/debugger.html/blob/master/public/js/utils/create-store.js#L6 ).

> You'll probably want to put the call to the server in the componentWillMount. 

From what I read here https://facebook.github.io/react/docs/component-specs.html#mounting-componentwillmount, `componentWillMount` is going to be executed before the render function, and so if there are changes on the state, render will only be called once. 
So, are saying I can dispatch the initial data fetching action from there, or that I can directly do the server call from there and dispatch the data retrieved action in the callback ?

If we're gonna use middlewares, do you have preferences on using thunk over promises for example&nbsp;? 

> It's probably worth breaking out a separate component that ConsoleApiCall delegates to for this.

Yes, I am creating a new `Table` component to handle this.

**Comment by linclark** [comment]
> So, are saying I can dispatch the initial data fetching action from there, or that I can directly do the server call from there and dispatch the data retrieved action in the callback?

I'm thinking we can directly do the server call from there. You can see an [example](https://facebook.github.io/react/tips/initial-ajax.html) in the React docs.

That said, you're closer to the code on this, so if you think Redux async actions makes more sense we can think about it more.

**Comment by nchevobbe** [comment]
> Btw, we should make sure to cover all of the test cases in browser_webconsole_output_table.js

I think it would make sense to have a unit test for the `populateTableData` equivalent, because browser_webconsole_output_table assume the data is in a specific shape.

**Comment by nchevobbe** [comment]
There is something weird in the current console : we only fetch the full set of data if the grip is an object or an array (
http://searchfox.org/mozilla-central/source/devtools/client/webconsole/console-output.js#1800 )

This means that for Map, Set, WeakMap, WeakSet, we only output what's in the `preview` property in the grip, which, for now, is limited to 10 items. 

Maybe we do this on purpose ? I can't see really why we would want such things. As a user, I would expect to work the same than for a simple array. 
From a code point of view, it would be more consistent for us to always retrieve the full set of data from the grip , no matter its type. I am gonna to do it this way for now, rolling back won't be a big deal if we decide to keep the current behavior.

FYI, there's nothing really precise in the spec (https://console.spec.whatwg.org/#dom-console-table), and Chrome simply handle those types as a console.log call.

**Comment by bgrins** [comment]
> Maybe we do this on purpose ? I can't see really why we would want such things. As a user, I would expect to work the same than for a simple array. 

I don't think much is intentional here - I wouldn't try to copy our current implementation directly.  Some more links:
- a list of differences: https://github.com/whatwg/console/blob/master/NOTES.md#consoletable---printing-of-strings.  In most of these cases, I think the Chrome output is better.
- some more analysis: https://github.com/whatwg/console/issues/21

**Comment by linclark** [comment]
This will land in m-c in [Bug 1305499](https://bugzilla.mozilla.org/show_bug.cgi?id=1305499)
