### ISSUE TITLE
Add support for console.trace()

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#66]
- Testing string: 

```
data:text/html;charset=utf-8,<script>function foo() {console.trace()}; foo()</script>
```
- [HTML and packets](https://github.com/linclark/webconsole-rdp/tree/master/data/consoleAPICall/console-trace)
- [Integration point](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1284)

**Comment by linclark** [comment]
@nchevobbe I think you're working on this, but correct me if I'm wrong.

**Comment by nchevobbe** [comment]
I am, just need to figure out how to import/reference toolbox's `viewSourceInDebugger` (http://searchfox.org/mozilla-central/source/devtools/client/framework/toolbox.js#2284)

**Comment by linclark** [comment]
It might be worth posting a WIP PR... that sounds like it could be related to some of the location stuff.

**Comment by bgrins** [comment]
I am, just need to figure out how to import/reference toolbox's viewSourceInDebugger (http://searchfox.org/mozilla-central/source/devtools/client/framework/toolbox.js#2284)

We could pass a reference to `toolbox` into the `NewConsoleOutput` constructor and then send `viewSourceInDebugger` down as props to various components.

**Comment by nchevobbe** [comment]
Yes, I was hacking in this way. @linclark I think you landed the new test architecture right ? So maybe I should add test for console.trace (you said I could skip them since you were working on the switch) ?

**Comment by linclark** [comment]
> @linclark I think you landed the new test architecture right ?

There are two more PRs waiting to land, #166 and #171

**Comment by linclark** [comment]
@nchevobbe those test PRs have landed, but there is some additional infra that will help with tests that will land in #178.

I think we can probably land this without the tests and then add them in the next sprint. That will make it possible to close out this sprint.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1291358](https://bugzilla.mozilla.org/show_bug.cgi?id=1291358)

**Comment by linclark** [comment]
🎉
