### ISSUE TITLE
Add support for navigation marker

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#68]
Testing: 
    - Set `devtools.webconsole.persistlog` to true in about:config
    - Navigate to a different page
[HTML and packets](https://github.com/linclark/webconsole-rdp/tree/master/data/tabNavigated)
[Integration point](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1984)

**Comment by linclark** [comment]
For this, Chrome just adds a message saying `Navigated to <url>`. I think this would make things a lot simpler. @bgrins, any opposition?

**Comment by bgrins** [comment]
> For this, Chrome just adds a message saying Navigated to <url>. I think this would make things a lot simpler. @bgrins, any opposition?

Sure, that's OK with me.

**Comment by bgrins** [comment]
@linclark there isn't a webconsole packet associated yet with this (it's the 'will-navigate' event on the tab).  It's also different from normal logs in that there's no location.

So a couple of implementation questions: 
- Should we have a new 'service message' component (a sibling of console-api-call, evaluation-result, console-command)?  Seems very similar to console-command.
- And, should we inject some new packet structure to pass into MESSAGE_ADD?  Is there an example from the chrome taxonomy we could use?

**Comment by linclark** [comment]
It looks to me like chrome just [handles it as a console.log()](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/sdk/ResourceTreeModel.js?dr=C&q=ResourceTreeModel&sq=package:chromium&l=258).

**Comment by pelmers** [comment]
<img width="1270" alt="screen shot 2016-07-29 at 10 36 18 am" src="https://cloud.githubusercontent.com/assets/2406051/17257740/4f6eb32e-5578-11e6-8265-7a5d4dab035c.png">
In this example I added the message as a console-command, but it's not very distinguishable from the surroundings.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1295254](https://bugzilla.mozilla.org/show_bug.cgi?id=1295254)
