### ISSUE TITLE
Fix eslint errors

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#72]
`./mach eslint devtools/client/webconsole/new-console-output/`reveals `34 problems (30 errors, 4 warnings)`.
I guess we should have those fixed before landing upstream ( #56  ) ?

**Comment by linclark** [comment]
Good call, I added it to the milestone.

**Comment by nchevobbe** [comment]
Fixed by https://github.com/bgrins/gecko-dev/pull/74
