### ISSUE TITLE
Display consoleAPI calls done before the console view is opened

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#77]
In the old console, when the console is opened, it shows consoleAPI calls already executed.

**Comment by nchevobbe** [comment]
> I think this is handled by the _loadHistory function in jsterm ( https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/jsterm.js#82 ).
Please ignore this, the function handle the console inputs history.

**Comment by nchevobbe** [comment]
This is handled by the `displayCachedMessages` function in webconsole.js (https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1232).
We should find a way to have the packet here, and not only the message object, in order to dispatch it.

**Comment by bgrins** [comment]
The call to this.webConsoleClient.getCachedMessages should return an array of messages.    So if we short circuit that function and do a `this.webConsoleFrame.newConsoleOutput.dispatchMessageAdd`, it should work

**Comment by bgrins** [comment]
@pelmers is going to look at this

**Comment by pelmers** [comment]
#96
