### ISSUE TITLE
Make it possible to pass in a component for linking labels

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#86]
This is actually more a reps issue than a web console issue. It blocks #85.

Honza and I discussed this in London. The current thinking is this:
1. Pass in a component that renders labels. The props object it should expect is `{object, label}`.
2. If that is passed in to any component, pass it down to the children as well. This will make it possible for items inside and array or object to be directly linked to their variables view.
3. We probably also want to make the outer brackets/braces link and the more... link.

**Comment by nchevobbe** [comment]
So this is how I understand it. 
There would be a new component `LinkableTitle` (or alike), which should be passed to the Rep like : 

```
Rep({
  object: arg,
  linkableTitle  : LinkableTitle({
    label: "Array",
    object: arg,
    className: "rep-title",
    role: "presentation",
    ...
  })
});
```

This component would have a render function like : 

```
render: function () {
  const { object, label } = this.props;
  let props = Object.assign({
    onClick: openVariableView.bind(this, object)    // Or should this should passed as a prop too ?
  }, this.props);
  return DOM.a(props, label);
}
```

But then it's unclear to me how I should use this component to add the link on the curly brackets and the `more...` text.

If I take the render function in grip-array.js as an example, I could do : 

```
return (
  ObjectBox({className: "object"},
    this.props.linkableTitle, // The actual title
    LinkableTitle({
      object: this.props.object,
      label: "{",
      className: "objectLeftBrace",
      role: "presentation"
    }),
    props,
    LinkableTitle({
      object: this.props.object,
      label: "}",
      className: "objectRightBrace",
      role: "presentation"
    })
  )
);
```

Or should I just reuse this.props.linkableTitle, clone it and only re-assigning the label (and the other presentational props, ..) ? 

I'm afraid I get this wrong, and I want to make sure to understand it well before to get into any coding.

**Comment by linclark** [comment]
I think the confusion probably comes from how I described it. I'd say a property name like `objectLinkComponent` might make sense.

When you use LinkableTitle as a function in the snippet below, you're creating a React element from it.

```
Rep({
  object: arg,
  linkableTitle  : LinkableTitle({
    label: "Array",
    object: arg,
    className: "rep-title",
    role: "presentation",
    ...
  })
});
```

Instead, what you'd want to do is pass in the component itself, e.g.

```
Rep({
  object: arg,
  objectLinkComponent: VariablesViewLink
});
```

Then this can be used inside of the Array component. Let me know if it's still confusing.

**Comment by nchevobbe** [comment]
Okay thank you, I think I got it.
In the Rep, I can get the component : 

`let linkableComponent = this.props.objectLinkComponent || DOM.span;`
And then use it to create the React Element with it, for the title, the curly brackets, and so on : 

```
return (
  ObjectBox({className: "object"},
    linkableComponent({
      objectActor: object,
      label: object.class
    }),
    linkableComponent({
      objectActor: object,
      label: "{",
      className: "objectLeftBrace",
      role: "presentation"
    }),
    props,
    linkableComponent({
      objectActor: object,
      label: "}",
      className: "objectRightBrace",
      role: "presentation"
    })
  }
));
```

**Comment by linclark** [comment]
Yes, that's exactly it. I think something a little more descriptive than `linkableComponent` might be good. We're planning to remove `ObjectLink`, so we could reuse that name as `objectLink`.

**Comment by linclark** [comment]
This work is currently being tracked in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1283123
