### ISSUE TITLE
Add support for "activate timestamp" preference

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#88]
Displays a timestamp with the `HH:ii:ss,.SSS` before the log message when the `devtools.webconsole.timestampMessages`is set to TRUE

Test to be rewritten:
- [ ] browser_webconsole_expandable_timestamps.js

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307871](https://bugzilla.mozilla.org/show_bug.cgi?id=1307871)
