### ISSUE TITLE
Add a file location component

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#89]
Add a component which would display the file and line number the message is logged from
Clicking on the location should open the file in the debugger at the specified line

This component would be displayed at the end of each log message, and at the end of each stacktrace item  when console.trace() is called

**Comment by nchevobbe** [comment]
Maybe we should wait for the new debugger to be accessible in the repo ? I don't know if the implementation of opening the debugger with a given file at a given line will be different from what we have now, but since the debugger and the new console have similar "deadline", it'd be better to not do this work twice.

**Comment by nchevobbe** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=670002 , which aims to handle source map in the current webconsole

**Comment by linclark** [comment]
Now that the work on source maps in the current console is done, @jbhoosreddy will be taking this on.

**Comment by jsnajdr** [comment]
There are `frame.js` and 'stack-trace.js`React components in`/devtools/client/shared/components` that do everything you need. Just plug them into the console markup.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1294498](https://bugzilla.mozilla.org/show_bug.cgi?id=1294498)
