### ISSUE TITLE
Add collapsible stacktrace for console.error/trace messages

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#90]
Depends on https://github.com/devtools-html/gecko-dev/issues/66 for the stacktrace container, and on #91 for the toggler/expander component ( which we should feed with the title props set to l10n.getStr("messageToggleDetails") )

**Comment by linclark** [comment]
Bumping this to sprint 3 since I added Mocha tests to this sprint.

**Comment by nchevobbe** [comment]
I was thinking about this and how to design the expanded/collapsed state of the stacktrace.
Adding a `open` property on the ConsoleMessage record seems to be the easiest way to do this. I would then only have to dispatch an action from the collapse button and handle the CSS class accordingly.
However it may clutter the message record with data relative to the application state, not the message itself , so I'm not sure it's something we want ?

The other solution I can think of would be to have a `opened` property (and a reducer) on the state which would be an array of the message ids which should be open, and add/remove entry on it when hitting the collapse button.

@linclark could you point me into the correct direction ?

**Comment by linclark** [comment]
This is a really good question.

We will also have inline object inspection in phase 2. Once we have that, we'll likely need to keep track of which objects have been toggled open. Because of that, I'm thinking that keeping track of message UI state separately (like you suggest with the `opened` propery) might make sense.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1294499](https://bugzilla.mozilla.org/show_bug.cgi?id=1294499)

**Comment by nchevobbe** [comment]
Closed #90 via #206.
