### ISSUE TITLE
Add a collapser/toggler/twisty component

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#91]
Add a component for expanding/collapsing a container (be it an error stacktrace or a console.group ) The existing markup looks like : 
`<a class="theme-twisty" href="#" title=""></a>`

**Comment by linclark** [comment]
@nchevobbe if you want to take this on that would be 💯

**Comment by nchevobbe** [comment]
@linclark sure !

**Comment by nchevobbe** [comment]
I think I'm gonna handle https://github.com/devtools-html/gecko-dev/issues/90 in the same PR.

**Comment by linclark** [comment]
Ah good, I was thinking about that. I think it makes a lot of sense.
