### ISSUE TITLE
Show message when console API has been replaced

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#95]
See the following bits in the webconsole.js frontend for when this is detected / shown in the current frontend:

this._hasNativeConsoleAPI
logWarningAboutReplacedAPI
packet.nativeConsoleAPI

**Comment by linclark** [comment]
This will land in m-c in [Bug 1307874](https://bugzilla.mozilla.org/show_bug.cgi?id=1307874)
