### ISSUE TITLE
Add a waitForMessages function for end-to-end testing

### ISSUE THREAD

**Issue by bgrins** [firefox-devtools/original-console-fork#99]
We should see if it's possible to run some of the integration tests by simulating the same `new-messages` event and making changes to head.js without modifying all of the tests.

**Comment by linclark** [comment]
I think we've scoped this one down to just "Get an end-to-end test working". My understanding from our conversation is that we're no longer trying to run the existing tests on the new frontend. @bgrins correct me if I'm wrong.

**Comment by linclark** [comment]
This will land in m-c in [Bug 1292325](https://bugzilla.mozilla.org/show_bug.cgi?id=1292325)

**Comment by bgrins** [comment]
We can include talos runs on the try push in the bug with `-t all` on the try syntax

**Comment by linclark** [comment]
✨
